apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80 
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: suggestionapiacr.azurecr.io/suggestionazureapi:#{Build.BuildId}#
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ConnectionStrings__Local
          valueFrom: 
            secretKeyRef:
              name: api-db
              key: connectionstring
        imagePullPolicy : Always
        ports:
        - containerPort: 80
        - containerPort: 443
        # livenessProbe:
          # httpGet:
            # path: /health
            # port: 80
          # initialDelaySeconds: 5
          # periodSeconds: 3
        # readinessProbe:
          # httpGet:
            # path: /health
            # port: 80
          # initialDelaySeconds: 5
          # periodSeconds: 3
      imagePullSecrets:
        - name: acr-secret